spring.application.name=ProjetoMentis
spring.datasource.url=jdbc:postgresql://localhost:5432/ProjetoMentis
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update