spring.application.name=ProjetoMentis
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ProjetoMentis}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update